# Generated by Django 3.2.9 on 2021-11-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellido',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
