# Generated by Django 3.2.9 on 2021-11-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20211129_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_realizar', models.CharField(max_length=20)),
                ('profesor', models.CharField(max_length=20)),
                ('horarios', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InformacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_afiliado', models.CharField(max_length=20)),
                ('obra_social', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuario',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
