# Generated by Django 3.2.9 on 2021-11-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211129_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='edad',
            new_name='dni',
        ),
    ]
